    ###

GET http://localhost:8080/api/orders

###
GET http://localhost:8080/api/orders/8
### get by orderdate
GET http://localhost:8080/api/orders/date/2026-01-06
###
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "clientId": 1004,
  "method": "CARRYOUT",
  "details": [
    { "pizzaId": 5, "quantity": 1},
    { "pizzaId": 4, "quantity": 2 }
  ]
}



### delete
DELETE http://localhost:8080/api/orders/17

